CREATE TABLE IF NOT EXISTS self_healing_knowledge_base (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  healing_pattern_id VARCHAR(100) UNIQUE NOT NULL,
  trigger_condition JSONB NOT NULL DEFAULT '{}'::jsonb,
  trigger_type VARCHAR(50) NOT NULL CHECK (trigger_type in ('anomaly_detected','threat_confirmed','performance_degradation','integrity_failure','canary_triggered','agent_compromised','schema_violation_spike','injection_rate_spike','availability_threat')),
  healing_strategy VARCHAR(50) NOT NULL CHECK (healing_strategy in ('auto_isolate','auto_rollback','auto_reinstate','auto_scale','signature_update','baseline_recalibration','traffic_reroute','emergency_lockdown','graduated_response','deception_engage')),
  healing_steps JSONB NOT NULL DEFAULT ARRAY[]::text,
  estimated_duration_seconds INTEGER NOT NULL DEFAULT 30,
  requires_human_approval BOOLEAN NOT NULL DEFAULT FALSE,
  approval_timeout_seconds INTEGER NOT NULL DEFAULT 300,
  rollback_procedure JSONB NOT NULL DEFAULT ARRAY[]::text,
  success_criteria JSONB NOT NULL DEFAULT ARRAY[]::text,
  failure_fallback_strategy VARCHAR(100),
  usage_count INTEGER NOT NULL DEFAULT 0,
  success_count INTEGER NOT NULL DEFAULT 0,
  failure_count INTEGER NOT NULL DEFAULT 0,
  avg_resolution_seconds INTEGER,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTZ NOT NULL DEFAULT NOW(),
  last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS system_health_sovereign_monitor (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  measurement_id UUID UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
  timestamp TIMESTZ NOT NULL DEFAULT NOW(),
  layer_id VARCHAR(50) NOT NULL,
  component_id VARCHAR(100) NOT NULL,
  health_score INTEGER NOT NULL CHECK (health_score BETWEEN 0 AND 100),
  availability_percent DECIMAL(6,3) NOT NULL,
  latency_p50_ms DECIMAL(8,3),
  latency_p95_ms DECIMAL(8,3),
  latency_p99_ms DECIMAL(8,3),
  error_rate DECIMAL(7,6),
  throughput_rps DECIMAL(10,3),
  security_events_last_minute INTEGER NOT NULL DEFAULT 0,
  active_threats INTEGER NOT NULL DEFAULT 0,
  self_healing_active BOOLEAN NOT NULL DEFAULT FALSE,
  degraded_components JSONB NOT NULL DEFAULT ARRAY[]::text,
  auto_mitigations_active JSONB NOT NULL DEFAULT ARRAY[]::text,
  overall_system_status VARCHAR(20) NOT NULL CHECK (overall_system_status in ('sovereign','nominal','degraded','recovering','under_attack','emergency'))
);

CREATE TABLE IF NOT EXISTS sovereign_incident_command (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  incident_id VARCHAR(60) UNIQUE NOT NULL DEFAULT 'INC-' || encode(gen_random_bytes(12),'hex'),
  declared_at TIMESTZ NOT NULL DEFAULT NOW(),
  severity VARCHAR(20) NOT NULL CHECK (severity in ('P0_existential','P1_critical','P2_high','P3_medium','P4_low','P5_informational')),
  status VARCHAR(30) NOT NULL DEFAULT 'auto_responding' CHECK (status in ('auto_detected','auto_responding','auto_contained','human_triaging','actively_investigating','contained','eradicating','recovering','post_incident_analysis','closed','false_positive','intelligence_operation')),
  incident_type VARCHAR(200) NOT NULL,
  attack_kb_id UUID REFERENCES prompt_attack_knowledge_base(id),
  campaign_id UUID REFERENCES attack_campaign_tracker(id),
  affected_tenants JSONB NOT NULL DEFAULT ARRAY[]::text,
  affected_agents JSONB NOT NULL DEFAULT ARRAY[]::text,
  affected_layers JSONB NOT NULL DEFAULT ARRAY[]::text,
  initial_attack_vector TEXT,
  initial_ioc TEXT NOT NULL,
  kill_chain_stage_at_detection VARCHAR(50),
  attacker_objectives_assessed JSONB NOT NULL DEFAULT ARRAY[]::text,
  sophistication_assessment VARCHAR(30),
  auto_response_timeline JSONB NOT NULL DEFAULT ARRAY[]::text,
  human_response_timeline JSONB NOT NULL DEFAULT ARRAY[]::text,
  evidence_collected JSONB NOT NULL DEFAULT ARRAY[]::text,
  iocs_extracted JSONB NOT NULL DEFAULT ARRAY[]::text,
  threat_intel_updated JSONB NOT NULL DEFAULT ARRAY[]::text,
  containment_measures_active JSONB NOT NULL DEFAULT ARRAY[]::text,
  impact_scope JSONB NOT NULL DEFAULT '{}'::jsonb,
  business_impact_assessment TEXT,
  root_cause TEXT,
  contributing_vulnerabilities JSONB NOT NULL DEFAULT ARRAY[]::text,
  lessons_learned TEXT,
  defensive_improvements JSONB NOT NULL DEFAULT ARRAY[]::text,
  signature_updates_generated JSONB NOT NULL DEFAULT ARRAY[]::text,
  assigned_to VARCHAR(100),
  escalated_to VARCHAR(100),
  external_parties_notified JSONB NOT NULL DEFAULT ARRAY[]::text,
  resolved_at TIMESTZ,
  mttd_seconds INTEGER,
  mttr_seconds INTEGER,
  auto_contained BOOLEAN NOT NULL DEFAULT FALSE,
  required_human_intervention BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS sovereign_response_playbooks (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  playbook_id VARCHAR(100) UNIQUE NOT NULL,
  playbook_name VARCHAR(300) NOT NULL,
  playbook_version INTEGER NOT NULL DEFAULT 1,
  applicable_threat_classes JSONB NOT NULL DEFAULT ARRAY[]::text,
  applicable_severity_levels JSONB NOT NULL DEFAULT ARRAY[]::text,
  trigger_conditions JSONB NOT NULL DEFAULT '{}'::jsonb,
  phases JSONB NOT NULL DEFAULT ARRAY[]::text,
  auto_execution_allowed BOOLEAN NOT NULL DEFAULT TRUE,
  auto_execution_max_severity VARCHAR(20) NOT NULL DEFAULT 'P2_high',
  human_approval_required_above VARCHAR(20) NOT NULL DEFAULT 'P1_critical',
  approval_timeout_seconds INTEGER NOT NULL DEFAULT 300,
  default_approval_action VARCHAR(20) NOT NULL DEFAULT 'execute',
  rollback_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  rollback_triggers JSONB NOT NULL DEFAULT ARRAY[]::text,
  intelligence_capture_steps JSONB NOT NULL DEFAULT ARRAY[]::text,
  notification_matrix JSONB NOT NULL DEFAULT '{}'::jsonb,
  success_criteria JSONB NOT NULL DEFAULT ARRAY[]::text,
  success_rate DECIMAL(5,4),
  avg_execution_seconds INTEGER,
  last_triggered TIMESTZ,
  trigger_count INTEGER NOT NULL DEFAULT 0,
  tested_at TIMESTZ,
  tested_successfully BOOLEAN,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sovereign_forensics_vault (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  evidence_id VARCHAR(100) UNIQUE NOT NULL DEFAULT 'EVD-' || encode(gen_random_bytes(16),'hex'),
  incident_id VARCHAR(60) NOT NULL REFERENCES sovereign_incident_command(incident_id),
  collected_at TIMESTZ NOT NULL DEFAULT NOW(),
  collection_agent_id UUID,
  evidence_type VARCHAR(60) NOT NULL CHECK (evidence_type in ('session_complete_reconstruction','prompt_conversation_verbatim','agent_mesh_communication_log','database_state_snapshot','memory_heap_capture','network_flow_reconstruction','canary_extraction_full_context','output_stream_verbatim','behavioral_timeline','attack_pattern_fingerprint')),
  evidence_sha256 VARCHAR(64) NOT NULL,
  evidence_sha3_512 VARCHAR(128) NOT NULL,
  evidence_size_bytes BIGINT NOT NULL,
  encrypted BOOLEAN NOT NULL DEFAULT TRUE,
  encryption_algorithm VARCHAR(50) NOT NULL DEFAULT 'AES-256-GCM',
  encryption_key_reference VARCHAR(200) NOT NULL,
  storage_path_encrypted TEXT NOT NULL,
  immutability_guaranteed BOOLEAN NOT NULL DEFAULT TRUE,
  blockchain_anchor_hash VARCHAR(128),
  retention_days INTEGER NOT NULL DEFAULT 730,
  legal_hold BOOLEAN NOT NULL DEFAULT FALSE,
  legal_hold_reason TEXT,
  expires_at TIMESTZ NOT NULL,
  chain_of_custody JSONB NOT NULL DEFAULT ARRAY[]::text,
  integrity_check_count INTEGER NOT NULL DEFAULT 0,
  last_integrity_check TIMESTZ,
  integrity_violations INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS signature_evolution_engine (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  evolution_event_id VARCHAR(100) UNIQUE NOT NULL DEFAULT encode(gen_random_bytes(16),'hex'),
  triggered_at TIMESTZ NOT NULL DEFAULT NOW(),
  trigger_source VARCHAR(50) NOT NULL CHECK (trigger_source in ('new_attack_detected','canary_triggered','false_positive_threshold','threat_intel_update','penetration_test_finding','honeypot_intelligence','manual_security_research')),
  evolution_type VARCHAR(50) NOT NULL CHECK (evolution_type in ('new_signature_created','existing_signature_updated','signature_retired','threshold_adjusted','pattern_refined','new_attack_class_added','false_positive_remediation','sensitivity_calibrated')),
  source_incident_id VARCHAR(60),
  source_canary_id UUID REFERENCES canary_sovereignty_network(id),
  source_intelligence JSONB NOT NULL DEFAULT '{}'::jsonb,
  signatures_affected JSONB NOT NULL DEFAULT ARRAY[]::text,
  changes_applied JSONB NOT NULL DEFAULT ARRAY[]::text,
  validation_results JSONB NOT NULL DEFAULT '{}'::jsonb,
  expected_fpr_impact DECIMAL(5,4),
  expected_tpr_impact DECIMAL(5,4),
  deployed_to_production BOOLEAN NOT NULL DEFAULT FALSE,
  deployment_timestamp TIMESTZ,
  rollback_available BOOLEAN NOT NULL DEFAULT TRUE,
  approved_by VARCHAR(100),
  approval_timestamp TIMESTZ,
  performance_impact_assessment JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS sovereign_security_intelligence (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  window_type VARCHAR(20) NOT NULL CHECK (window_type in ('realtime_1m','rolling_5m','rolling_15m','rolling_1h','daily','weekly','monthly','quarterly')),
  window_start TIMESTZ NOT NULL,
  window_end TIMESTZ NOT NULL,
  total_requests BIGINT NOT NULL DEFAULT 0,
  passed_requests BIGINT NOT NULL DEFAULT 0,
  blocked_requests BIGINT NOT NULL DEFAULT 0,
  sanitized_requests BIGINT NOT NULL DEFAULT 0,
  honeypot_engaged INTEGER NOT NULL DEFAULT 0,
  deception_operations INTEGER NOT NULL DEFAULT 0,
  injection_attempts BIGINT NOT NULL DEFAULT 0,
  unique_attacker_fingerprints INTEGER NOT NULL DEFAULT 0,
  unique_attacker_ips INTEGER NOT NULL DEFAULT 0,
  canary_triggers INTEGER NOT NULL DEFAULT 0,
  sentinel_extractions INTEGER NOT NULL DEFAULT 0,
  cross_tenant_violations INTEGER NOT NULL DEFAULT 0,
  agent_anomalies INTEGER NOT NULL DEFAULT 0,
  agent_self_healings INTEGER NOT NULL DEFAULT 0,
  incidents_p0 INTEGER NOT NULL DEFAULT 0,
  incidents_p1 INTEGER NOT NULL DEFAULT 0,
  incidents_p2 INTEGER NOT NULL DEFAULT 0,
  incidents_auto_contained INTEGER NOT NULL DEFAULT 0,
  avg_mttd_seconds DECIMAL(10,2),
  avg_mttr_seconds DECIMAL(10,2),
  system_availability_percent DECIMAL(7,4) NOT NULL DEFAULT 100.0,
  false_positive_rate DECIMAL(7,6) NOT NULL DEFAULT 0.0,
  true_positive_rate DECIMAL(7,6) NOT NULL DEFAULT 0.0,
  precision_score DECIMAL(7,6),
  f1_security_score DECIMAL(7,6),
  top_threat_classes JSONB NOT NULL DEFAULT ARRAY[]::text,
  emerging_attack_patterns JSONB NOT NULL DEFAULT ARRAY[]::text,
  geographic_threat_map JSONB NOT NULL DEFAULT '{}'::jsonb,
  threat_trend_direction VARCHAR(20) CHECK (threat_trend_direction in ('decreasing','stable','increasing','spiking','critical')),
  signatures_updated_this_period INTEGER NOT NULL DEFAULT 0,
  intelligence_value_generated DECIMAL(8,4) NOT NULL DEFAULT 0.0,
  computed_at TIMESTZ NOT NULL DEFAULT NOW()
);
