CREATE TABLE IF NOT EXISTS output_sovereignty_scanner (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  scan_id UUID UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
  request_id UUID NOT NULL,
  tenant_id UUID NOT NULL,
  session_id UUID NOT NULL,
  turn_number INTEGER NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  raw_output_sha256 VARCHAR(64) NOT NULL,
  raw_output_token_count INTEGER,
  raw_output_entropy DECIMAL(6,4) NOT NULL,
  schema_compliant BOOLEAN NOT NULL DEFAULT FALSE,
  schema_version_found VARCHAR(20),
  schema_violations JSONB NOT NULL DEFAULT ARRAY[]::text[],
  pii_detected JSONB NOT NULL DEFAULT '{}'::jsonb,
  secrets_detected JSONB NOT NULL DEFAULT '{}'::jsonb,
  canary_tokens_detected JSONB NOT NULL DEFAULT ARRAY[]::text[],
  sentinel_tokens_detected JSONB NOT NULL DEFAULT ARRAY[]::text[],
  system_prompt_fragments JSONB NOT NULL DEFAULT ARRAY[]::text[],
  constitutional_content_leak BOOLEAN NOT NULL DEFAULT FALSE,
  cross_tenant_contamination JSONB NOT NULL DEFAULT ARRAY[]::text[],
  covert_channel_indicators JSONB NOT NULL DEFAULT ARRAY[]::text,
  steganographic_patterns JSONB NOT NULL DEFAULT ARRAY[]::text,
  encoding_anomalies JSONB NOT NULL DEFAULT ARRAY[]::text,
  url_analysis JSONB NOT NULL DEFAULT '{}'::jsonb,
  ssrf_risk_targets JSONB NOT NULL DEFAULT ARRAY[]::text,
  code_analysis JSONB NOT NULL DEFAULT '{}'::jsonb,
  dangerous_functions JSONB NOT NULL DEFAULT ARRAY[]::text,
  injection_artifacts JSONB NOT NULL DEFAULT ARRAY[]::text,
  semantic_coherence_score DECIMAL(5,4),
  topic_drift_score DECIMAL(5,4),
  response_manipulation_indicators JSONB NOT NULL DEFAULT ARRAY[]::text,
  exfiltration_risk_score INTEGER NOT NULL DEFAULT 0,
  total_risk_score INTEGER NOT NULL CHECK (total_risk_score BETWEEN 0 AND 100),
  sanitization_applied JSONB NOT NULL DEFAULT ARRAY[]::text,
  final_output_sha256 VARCHAR(64),
  action VARCHAR(30) NOT NULL CHECK (action IN ('pass','minor_sanitize','major_sanitize','blocked','escalated','quarantined','honeypot_intercepted')),
  processing_time_ms INTEGER NOT NULL,
  downstream_threat_intel_updated BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS tenant_sovereignty_profiles (
  tenant_id UUID PRIMARY KEY,
  tenant_code VARCHAR(100) UNIQUE NOT NULL,
  tenant_tier VARCHAR(20) NOT NULL CHECK (tenant_tier IN ('standard','professional','enterprise','government','sovereign')),
  data_classification VARCHAR(30) NOT NULL CHECK (data_classification IN ('public','internal','confidential','secret','top_secret','compartmented')),
  security_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
  allowed_models JSONB NOT NULL DEFAULT ARRAY[]::text,
  allowed_capabilities JSONB NOT NULL DEFAULT ARRAY[]::text,
  allowed_tables JSONB NOT NULL DEFAULT ARRAY[]::text,
  row_level_security_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
  column_restrictions JSONB NOT NULL DEFAULT '{}'::jsonb,
  max_tokens_per_request INTEGER NOT NULL DEFAULT 4000,
  max_requests_per_minute INTEGER NOT NULL DEFAULT 120,
  max_concurrent_sessions INTEGER NOT NULL DEFAULT 10,
  data_residency_region VARCHAR(50),
  geo_restrictions JSONB NOT NULL DEFAULT ARRAY[]::text,
  ip_whitelist JSONB NOT NULL DEFAULT ARRAY[]::text,
  require_mfa BOOLEAN NOT NULL DEFAULT TRUE,
  require_signed_requests BOOLEAN NOT NULL DEFAULT TRUE,
  require_encrypted_channel BOOLEAN NOT NULL DEFAULT TRUE,
  canary_tokens_deployed INTEGER NOT NULL DEFAULT 0,
  honeypots_active INTEGER NOT NULL DEFAULT 0,
  audit_retention_days INTEGER NOT NULL DEFAULT 365,
  compliance_frameworks JSONB NOT NULL DEFAULT ARRAY[]::text,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS deception_asset_network (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  asset_id VARCHAR(100) UNIQUE NOT NULL,
  asset_generation INTEGER NOT NULL DEFAULT 1,
  asset_type VARCHAR(60) NOT NULL CHECK (asset_type IN ('honeypot_api_endpoint','phantom_admin_credential','ghost_database_table','decoy_agent_identity','fake_constitutional_override_key','trap_prompt_template','ghost_tenant_namespace','phantom_internal_route','lure_documentation_page','intelligence_grade_canary_cluster')),
  asset_value TEXT NOT NULL,
  asset_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  placement_layer VARCHAR(100) NOT NULL,
  placement_strategy TEXT NOT NULL,
  attacker_path_to_discovery TEXT NOT NULL,
  sophistication_tier VARCHAR(20) NOT NULL CHECK (sophistication_tier in ('basic','intermediate','advanced','elite','nation_state_grade')),
  expected_attacker_profile VARCHAR(200),
  intelligence_objectives JSONB NOT NULL DEFAULT ARRAY[]::text,
  engagement_protocol TEXT,
  containment_measures JSONB NOT NULL DEFAULT ARRAY[]::text,
  trigger_count INTEGER NOT NULL DEFAULT 0,
  unique_attacker_ips INTEGER NOT NULL DEFAULT 0,
  last_triggered TIMESTAMPTZ,
  intelligence_gathered_value DECIMAL(5,4) NOT NULL DEFAULT 0.0,
  effectiveness_score DECIMAL(5,4),
  rotation_interval_hours INTEGER NOT NULL DEFAULT 72,
  next_rotation_at TIMESTZ NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS deception_attacker_intelligence (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  intelligence_id UUID UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
  timestamp TIMESTZ NOT NULL DEFAULT NOW(),
  asset_id UUID NOT NULL REFERENCES deception_asset_network(id),
  attacker_session_id UUID NOT NULL,
  attacker_ip INET NOT NULL,
  attacker_fingerprint_id UUID REFERENCES behavioral_fingerprint_engine(id),
  attacker_tenant_id UUID,
  engagement_duration_seconds INTEGER,
  pre_engagement_recon JSONB NOT NULL DEFAULT ARRAY[]::text,
  engagement_sequence JSONB NOT NULL DEFAULT ARRAY[]::text,
  post_engagement_behavior JSONB NOT NULL DEFAULT ARRAY[]::text,
  tools_identified JSONB NOT NULL DEFAULT ARRAY[]::text,
  techniques_observed JSONB NOT NULL DEFAULT ARRAY[]::text,
  objectives_inferred JSONB NOT NULL DEFAULT ARRAY[]::text,
  sophistication_assessed VARCHAR(30),
  automation_detected BOOLEAN,
  human_operator_suspected BOOLEAN,
  apt_indicators JSONB NOT NULL DEFAULT ARRAY[]::text,
  data_exfiltration_attempted JSONB NOT NULL ARRAY[]::text,
  lateral_movement_attempted BOOLEAN NOT NULL DEFAULT FALSE,
  campaign_correlation_id UUID REFERENCES attack_campaign_tracker(id),
  intelligence_value_score DECIMAL(5,4) NOT NULL DEFAULT 0.0,
  threat_intel_contribution JSONB NOT NULL DEFAULT '{}'::jsonb,
  shared_with_threat_intel BOOLEAN NOT NULL DEFAULT FALSE,
  incident_id VARCHAR(100)
);
